/**
 * @fuegokit/tokens 0.20.0
 * Do not edit directly
 * Generated on Sat, 11 May 2024 01:30:46 GMT
 */

const tokensObject: Record<string, string> = {
  "radii.0": "radii-0",
  "radii-0": "radii-0",
  "radii.1": "radii-1",
  "radii-1": "radii-1",
  "radii.2": "radii-2",
  "radii-2": "radii-2",
  "radii.3": "radii-3",
  "radii-3": "radii-3",
  "radii.4": "radii-4",
  "radii-4": "radii-4",
  "radii.5": "radii-5",
  "radii-5": "radii-5",
  "size.0": "size-0",
  "size-0": "size-0",
  "size.4": "size-4",
  "size-4": "size-4",
  "size.8": "size-8",
  "size-8": "size-8",
  "size.12": "size-12",
  "size-12": "size-12",
  "size.16": "size-16",
  "size-16": "size-16",
  "size.20": "size-20",
  "size-20": "size-20",
  "size.24": "size-24",
  "size-24": "size-24",
  "size.28": "size-28",
  "size-28": "size-28",
  "size.32": "size-32",
  "size-32": "size-32",
  "size.36": "size-36",
  "size-36": "size-36",
  "size.40": "size-40",
  "size-40": "size-40",
  "size.44": "size-44",
  "size-44": "size-44",
  "size.48": "size-48",
  "size-48": "size-48",
  "size.64": "size-64",
  "size-64": "size-64",
  "size.80": "size-80",
  "size-80": "size-80",
  "size.96": "size-96",
  "size-96": "size-96",
  "size.112": "size-112",
  "size-112": "size-112",
  "size.128": "size-128",
  "size-128": "size-128",
  "size.144": "size-144",
  "size-144": "size-144",
  "space.0": "space-0",
  "space-0": "space-0",
  "space.1": "space-1",
  "space-1": "space-1",
  "space.2": "space-2",
  "space-2": "space-2",
  "space.3": "space-3",
  "space-3": "space-3",
  "space.4": "space-4",
  "space-4": "space-4",
  "space.5": "space-5",
  "space-5": "space-5",
  "space.6": "space-6",
  "space-6": "space-6",
  "space.7": "space-7",
  "space-7": "space-7",
  "space.8": "space-8",
  "space-8": "space-8",
  "space.9": "space-9",
  "space-9": "space-9",
  "space.10": "space-10",
  "space-10": "space-10",
  "space.11": "space-11",
  "space-11": "space-11",
  "space.12": "space-12",
  "space-12": "space-12",
  "fontFamily.sansSerif": "fontFamily-sansSerif",
  "fontFamily-sansSerif": "fontFamily-sansSerif",
  "fontFamily.monospace": "fontFamily-monospace",
  "fontFamily-monospace": "fontFamily-monospace",
  "fontFamily.heading": "fontFamily-heading",
  "fontFamily-heading": "fontFamily-heading",
  "fontFamily.display": "fontFamily-display",
  "fontFamily-display": "fontFamily-display",
  "fontFamily.body": "fontFamily-body",
  "fontFamily-body": "fontFamily-body",
  "fontFamily.normal": "fontFamily-normal",
  "fontFamily-normal": "fontFamily-normal",
  "fontFamily.mono": "fontFamily-mono",
  "fontFamily-mono": "fontFamily-mono",
  "fontFamilies.sansSerif": "fontFamilies-sansSerif",
  "fontFamilies-sansSerif": "fontFamilies-sansSerif",
  "fontFamilies.monospace": "fontFamilies-monospace",
  "fontFamilies-monospace": "fontFamilies-monospace",
  "fontFamilies.title": "fontFamilies-title",
  "fontFamilies-title": "fontFamilies-title",
  "fontFamilies.body": "fontFamilies-body",
  "fontFamilies-body": "fontFamilies-body",
  "fontFamilies.normal": "fontFamilies-normal",
  "fontFamilies-normal": "fontFamilies-normal",
  "fontFamilies.mono": "fontFamilies-mono",
  "fontFamilies-mono": "fontFamilies-mono",
  "fontStack.sansSerif": "fontStack-sansSerif",
  "fontStack-sansSerif": "fontStack-sansSerif",
  "fontStack.monospace": "fontStack-monospace",
  "fontStack-monospace": "fontStack-monospace",
  "fontStack.title": "fontStack-title",
  "fontStack-title": "fontStack-title",
  "fontStack.body": "fontStack-body",
  "fontStack-body": "fontStack-body",
  "fontStack.normal": "fontStack-normal",
  "fontStack-normal": "fontStack-normal",
  "fontStack.mono": "fontStack-mono",
  "fontStack-mono": "fontStack-mono",
  "fontWeight.thin": "fontWeight-thin",
  "fontWeight-thin": "fontWeight-thin",
  "fontWeight.extraLight": "fontWeight-extraLight",
  "fontWeight-extraLight": "fontWeight-extraLight",
  "fontWeight.light": "fontWeight-light",
  "fontWeight-light": "fontWeight-light",
  "fontWeight.normal": "fontWeight-normal",
  "fontWeight-normal": "fontWeight-normal",
  "fontWeight.medium": "fontWeight-medium",
  "fontWeight-medium": "fontWeight-medium",
  "fontWeight.semiBold": "fontWeight-semiBold",
  "fontWeight-semiBold": "fontWeight-semiBold",
  "fontWeight.semibold": "fontWeight-semibold",
  "fontWeight-semibold": "fontWeight-semibold",
  "fontWeight.bold": "fontWeight-bold",
  "fontWeight-bold": "fontWeight-bold",
  "fontWeight.extraBold": "fontWeight-extraBold",
  "fontWeight-extraBold": "fontWeight-extraBold",
  "fontWeight.black": "fontWeight-black",
  "fontWeight-black": "fontWeight-black",
  "fontWeights.extraLight": "fontWeights-extraLight",
  "fontWeights-extraLight": "fontWeights-extraLight",
  "fontWeights.light": "fontWeights-light",
  "fontWeights-light": "fontWeights-light",
  "fontWeights.normal": "fontWeights-normal",
  "fontWeights-normal": "fontWeights-normal",
  "fontWeights.medium": "fontWeights-medium",
  "fontWeights-medium": "fontWeights-medium",
  "fontWeights.semibold": "fontWeights-semibold",
  "fontWeights-semibold": "fontWeights-semibold",
  "fontWeights.bold": "fontWeights-bold",
  "fontWeights-bold": "fontWeights-bold",
  "fontWeights.extraBold": "fontWeights-extraBold",
  "fontWeights-extraBold": "fontWeights-extraBold",
  "fontWeights.black": "fontWeights-black",
  "fontWeights-black": "fontWeights-black",
  "fontSize.0": "fontSize-0",
  "fontSize-0": "fontSize-0",
  "fontSize.1": "fontSize-1",
  "fontSize-1": "fontSize-1",
  "fontSize.2": "fontSize-2",
  "fontSize-2": "fontSize-2",
  "fontSize.3": "fontSize-3",
  "fontSize-3": "fontSize-3",
  "fontSize.4": "fontSize-4",
  "fontSize-4": "fontSize-4",
  "fontSize.5": "fontSize-5",
  "fontSize-5": "fontSize-5",
  "fontSize.6": "fontSize-6",
  "fontSize-6": "fontSize-6",
  "fontSize.7": "fontSize-7",
  "fontSize-7": "fontSize-7",
  "fontSize.8": "fontSize-8",
  "fontSize-8": "fontSize-8",
  "fontSize.9": "fontSize-9",
  "fontSize-9": "fontSize-9",
  "fontSize.10": "fontSize-10",
  "fontSize-10": "fontSize-10",
  "fontSize.11": "fontSize-11",
  "fontSize-11": "fontSize-11",
  "fontSize.12": "fontSize-12",
  "fontSize-12": "fontSize-12",
  "fontSize.13": "fontSize-13",
  "fontSize-13": "fontSize-13",
  "fontSizes.0": "fontSizes-0",
  "fontSizes-0": "fontSizes-0",
  "fontSizes.1": "fontSizes-1",
  "fontSizes-1": "fontSizes-1",
  "fontSizes.2": "fontSizes-2",
  "fontSizes-2": "fontSizes-2",
  "fontSizes.3": "fontSizes-3",
  "fontSizes-3": "fontSizes-3",
  "fontSizes.4": "fontSizes-4",
  "fontSizes-4": "fontSizes-4",
  "fontSizes.5": "fontSizes-5",
  "fontSizes-5": "fontSizes-5",
  "fontSizes.6": "fontSizes-6",
  "fontSizes-6": "fontSizes-6",
  "fontSizes.7": "fontSizes-7",
  "fontSizes-7": "fontSizes-7",
  "fontSizes.8": "fontSizes-8",
  "fontSizes-8": "fontSizes-8",
  "fontSizes.9": "fontSizes-9",
  "fontSizes-9": "fontSizes-9",
  "fontSizes.10": "fontSizes-10",
  "fontSizes-10": "fontSizes-10",
  "fontSizes.11": "fontSizes-11",
  "fontSizes-11": "fontSizes-11",
  "fontSizes.12": "fontSizes-12",
  "fontSizes-12": "fontSizes-12",
  "fontSizes.13": "fontSizes-13",
  "fontSizes-13": "fontSizes-13",
  "lineHeight.0": "lineHeight-0",
  "lineHeight-0": "lineHeight-0",
  "lineHeight.1": "lineHeight-1",
  "lineHeight-1": "lineHeight-1",
  "lineHeight.2": "lineHeight-2",
  "lineHeight-2": "lineHeight-2",
  "lineHeight.3": "lineHeight-3",
  "lineHeight-3": "lineHeight-3",
  "lineHeight.4": "lineHeight-4",
  "lineHeight-4": "lineHeight-4",
  "lineHeight.5": "lineHeight-5",
  "lineHeight-5": "lineHeight-5",
  "lineHeight.6": "lineHeight-6",
  "lineHeight-6": "lineHeight-6",
  "lineHeight.default": "lineHeight-default",
  "lineHeight-default": "lineHeight-default",
  "lineHeight.condensed": "lineHeight-condensed",
  "lineHeight-condensed": "lineHeight-condensed",
  "lineHeight.condensedUltra": "lineHeight-condensedUltra",
  "lineHeight-condensedUltra": "lineHeight-condensedUltra",
  "lineHeight.relaxed": "lineHeight-relaxed",
  "lineHeight-relaxed": "lineHeight-relaxed",
  "lineHeights.0": "lineHeights-0",
  "lineHeights-0": "lineHeights-0",
  "lineHeights.1": "lineHeights-1",
  "lineHeights-1": "lineHeights-1",
  "lineHeights.2": "lineHeights-2",
  "lineHeights-2": "lineHeights-2",
  "lineHeights.3": "lineHeights-3",
  "lineHeights-3": "lineHeights-3",
  "lineHeights.4": "lineHeights-4",
  "lineHeights-4": "lineHeights-4",
  "lineHeights.5": "lineHeights-5",
  "lineHeights-5": "lineHeights-5",
  "lineHeights.6": "lineHeights-6",
  "lineHeights-6": "lineHeights-6",
  "lineHeights.default": "lineHeights-default",
  "lineHeights-default": "lineHeights-default",
  "lineHeights.condensed": "lineHeights-condensed",
  "lineHeights-condensed": "lineHeights-condensed",
  "lineHeights.condensedUltra": "lineHeights-condensedUltra",
  "lineHeights-condensedUltra": "lineHeights-condensedUltra",
  "lineHeights.relaxed": "lineHeights-relaxed",
  "lineHeights-relaxed": "lineHeights-relaxed",
  "letterSpacing.0": "letterSpacing-0",
  "letterSpacing-0": "letterSpacing-0",
  "letterSpacing.1": "letterSpacing-1",
  "letterSpacing-1": "letterSpacing-1",
  "letterSpacing.2": "letterSpacing-2",
  "letterSpacing-2": "letterSpacing-2",
  "letterSpacing.3": "letterSpacing-3",
  "letterSpacing-3": "letterSpacing-3",
  "letterSpacing.4": "letterSpacing-4",
  "letterSpacing-4": "letterSpacing-4",
  "font.heading.xxsmall": "font-heading-xxsmall",
  "font-heading-xxsmall": "font-heading-xxsmall",
  "font.heading.xsmall": "font-heading-xsmall",
  "font-heading-xsmall": "font-heading-xsmall",
  "font.heading.small": "font-heading-small",
  "font-heading-small": "font-heading-small",
  "font.heading.medium": "font-heading-medium",
  "font-heading-medium": "font-heading-medium",
  "font.heading.large": "font-heading-large",
  "font-heading-large": "font-heading-large",
  "font.heading.xlarge": "font-heading-xlarge",
  "font-heading-xlarge": "font-heading-xlarge",
  "font.heading.xxlarge": "font-heading-xxlarge",
  "font-heading-xxlarge": "font-heading-xxlarge",
  "font.body.default": "font-body-default",
  "font-body-default": "font-body-default",
  "font.body.small": "font-body-small",
  "font-body-small": "font-body-small",
  "font.body.medium": "font-body-medium",
  "font-body-medium": "font-body-medium",
  "font.body.large": "font-body-large",
  "font-body-large": "font-body-large",
  "font.body.xlarge": "font-body-xlarge",
  "font-body-xlarge": "font-body-xlarge",
  "font.ui.default": "font-ui-default",
  "font-ui-default": "font-ui-default",
  "font.ui.small": "font-ui-small",
  "font-ui-small": "font-ui-small",
  "font.caption.default": "font-caption-default",
  "font-caption-default": "font-caption-default",
  "font.code.default": "font-code-default",
  "font-code-default": "font-code-default",
  "font.code.xsmall": "font-code-xsmall",
  "font-code-xsmall": "font-code-xsmall",
  "font.code.small": "font-code-small",
  "font-code-small": "font-code-small",
  "font.code.medium": "font-code-medium",
  "font-code-medium": "font-code-medium",
  "font.display.default": "font-display-default",
  "font-display-default": "font-display-default",
  "font.display.medium": "font-display-medium",
  "font-display-medium": "font-display-medium",
  "elevation.surface.default.default": "elevation-surface-default-default",
  "elevation-surface-default-default": "elevation-surface-default-default",
  "elevation.surface.default.hovered": "elevation-surface-default-hovered",
  "elevation-surface-default-hovered": "elevation-surface-default-hovered",
  "elevation.surface.default.pressed": "elevation-surface-default-pressed",
  "elevation-surface-default-pressed": "elevation-surface-default-pressed",
  "elevation.surface.sunken": "elevation-surface-sunken",
  "elevation-surface-sunken": "elevation-surface-sunken",
  "elevation.surface.raised.default": "elevation-surface-raised-default",
  "elevation-surface-raised-default": "elevation-surface-raised-default",
  "elevation.surface.raised.hovered": "elevation-surface-raised-hovered",
  "elevation-surface-raised-hovered": "elevation-surface-raised-hovered",
  "elevation.surface.raised.pressed": "elevation-surface-raised-pressed",
  "elevation-surface-raised-pressed": "elevation-surface-raised-pressed",
  "elevation.surface.overlay.default": "elevation-surface-overlay-default",
  "elevation-surface-overlay-default": "elevation-surface-overlay-default",
  "elevation.surface.overlay.hovered": "elevation-surface-overlay-hovered",
  "elevation-surface-overlay-hovered": "elevation-surface-overlay-hovered",
  "elevation.surface.overlay.pressed": "elevation-surface-overlay-pressed",
  "elevation-surface-overlay-pressed": "elevation-surface-overlay-pressed",
  "elevation.shadow.raised": "elevation-shadow-raised",
  "elevation-shadow-raised": "elevation-shadow-raised",
  "elevation.shadow.overlay": "elevation-shadow-overlay",
  "elevation-shadow-overlay": "elevation-shadow-overlay",
  "elevation.shadow.overflow.default": "elevation-shadow-overflow-default",
  "elevation-shadow-overflow-default": "elevation-shadow-overflow-default",
  "elevation.shadow.overflow.spread": "elevation-shadow-overflow-spread",
  "elevation-shadow-overflow-spread": "elevation-shadow-overflow-spread",
  "elevation.shadow.overflow.perimeter": "elevation-shadow-overflow-perimeter",
  "elevation-shadow-overflow-perimeter": "elevation-shadow-overflow-perimeter",
  "border.default": "border-default",
  "border-default": "border-default",
  "border.selected": "border-selected",
  "border-selected": "border-selected",
  "border.focused": "border-focused",
  "border-focused": "border-focused",
  "border.subtle": "border-subtle",
  "border-subtle": "border-subtle",
  "border.input": "border-input",
  "border-input": "border-input",
  "border.inverse": "border-inverse",
  "border-inverse": "border-inverse",
  "border.disabled": "border-disabled",
  "border-disabled": "border-disabled",
  "border.brand": "border-brand",
  "border-brand": "border-brand",
  "border.danger": "border-danger",
  "border-danger": "border-danger",
  "border.warning": "border-warning",
  "border-warning": "border-warning",
  "border.success": "border-success",
  "border-success": "border-success",
  "border.discovery": "border-discovery",
  "border-discovery": "border-discovery",
  "border.information": "border-information",
  "border-information": "border-information",
  "border.accent.blue": "border-accent-blue",
  "border-accent-blue": "border-accent-blue",
  "border.accent.red": "border-accent-red",
  "border-accent-red": "border-accent-red",
  "border.accent.orange": "border-accent-orange",
  "border-accent-orange": "border-accent-orange",
  "border.accent.yellow": "border-accent-yellow",
  "border-accent-yellow": "border-accent-yellow",
  "border.accent.green": "border-accent-green",
  "border-accent-green": "border-accent-green",
  "border.accent.purple": "border-accent-purple",
  "border-accent-purple": "border-accent-purple",
  "border.accent.teal": "border-accent-teal",
  "border-accent-teal": "border-accent-teal",
  "border.accent.magenta": "border-accent-magenta",
  "border-accent-magenta": "border-accent-magenta",
  "border.accent.gray": "border-accent-gray",
  "border-accent-gray": "border-accent-gray",
  "border.table.default": "border-table-default",
  "border-table-default": "border-table-default",
  "background.accent.blue.subtlest": "background-accent-blue-subtlest",
  "background-accent-blue-subtlest": "background-accent-blue-subtlest",
  "background.accent.blue.subtler": "background-accent-blue-subtler",
  "background-accent-blue-subtler": "background-accent-blue-subtler",
  "background.accent.blue.subtle": "background-accent-blue-subtle",
  "background-accent-blue-subtle": "background-accent-blue-subtle",
  "background.accent.blue.bolder": "background-accent-blue-bolder",
  "background-accent-blue-bolder": "background-accent-blue-bolder",
  "background.accent.red.subtlest": "background-accent-red-subtlest",
  "background-accent-red-subtlest": "background-accent-red-subtlest",
  "background.accent.red.subtler": "background-accent-red-subtler",
  "background-accent-red-subtler": "background-accent-red-subtler",
  "background.accent.red.subtle": "background-accent-red-subtle",
  "background-accent-red-subtle": "background-accent-red-subtle",
  "background.accent.red.bolder": "background-accent-red-bolder",
  "background-accent-red-bolder": "background-accent-red-bolder",
  "background.accent.orange.subtlest": "background-accent-orange-subtlest",
  "background-accent-orange-subtlest": "background-accent-orange-subtlest",
  "background.accent.orange.subtler": "background-accent-orange-subtler",
  "background-accent-orange-subtler": "background-accent-orange-subtler",
  "background.accent.orange.subtle": "background-accent-orange-subtle",
  "background-accent-orange-subtle": "background-accent-orange-subtle",
  "background.accent.orange.bolder": "background-accent-orange-bolder",
  "background-accent-orange-bolder": "background-accent-orange-bolder",
  "background.accent.yellow.subtlest": "background-accent-yellow-subtlest",
  "background-accent-yellow-subtlest": "background-accent-yellow-subtlest",
  "background.accent.yellow.subtler": "background-accent-yellow-subtler",
  "background-accent-yellow-subtler": "background-accent-yellow-subtler",
  "background.accent.yellow.subtle": "background-accent-yellow-subtle",
  "background-accent-yellow-subtle": "background-accent-yellow-subtle",
  "background.accent.yellow.bolder": "background-accent-yellow-bolder",
  "background-accent-yellow-bolder": "background-accent-yellow-bolder",
  "background.accent.green.subtlest": "background-accent-green-subtlest",
  "background-accent-green-subtlest": "background-accent-green-subtlest",
  "background.accent.green.subtler": "background-accent-green-subtler",
  "background-accent-green-subtler": "background-accent-green-subtler",
  "background.accent.green.subtle": "background-accent-green-subtle",
  "background-accent-green-subtle": "background-accent-green-subtle",
  "background.accent.green.bolder": "background-accent-green-bolder",
  "background-accent-green-bolder": "background-accent-green-bolder",
  "background.accent.purple.subtlest": "background-accent-purple-subtlest",
  "background-accent-purple-subtlest": "background-accent-purple-subtlest",
  "background.accent.purple.subtler": "background-accent-purple-subtler",
  "background-accent-purple-subtler": "background-accent-purple-subtler",
  "background.accent.purple.subtle": "background-accent-purple-subtle",
  "background-accent-purple-subtle": "background-accent-purple-subtle",
  "background.accent.purple.bolder": "background-accent-purple-bolder",
  "background-accent-purple-bolder": "background-accent-purple-bolder",
  "background.accent.teal.subtlest": "background-accent-teal-subtlest",
  "background-accent-teal-subtlest": "background-accent-teal-subtlest",
  "background.accent.teal.subtler": "background-accent-teal-subtler",
  "background-accent-teal-subtler": "background-accent-teal-subtler",
  "background.accent.teal.subtle": "background-accent-teal-subtle",
  "background-accent-teal-subtle": "background-accent-teal-subtle",
  "background.accent.teal.bolder": "background-accent-teal-bolder",
  "background-accent-teal-bolder": "background-accent-teal-bolder",
  "background.accent.magenta.subtlest": "background-accent-magenta-subtlest",
  "background-accent-magenta-subtlest": "background-accent-magenta-subtlest",
  "background.accent.magenta.subtler": "background-accent-magenta-subtler",
  "background-accent-magenta-subtler": "background-accent-magenta-subtler",
  "background.accent.magenta.subtle": "background-accent-magenta-subtle",
  "background-accent-magenta-subtle": "background-accent-magenta-subtle",
  "background.accent.magenta.bolder": "background-accent-magenta-bolder",
  "background-accent-magenta-bolder": "background-accent-magenta-bolder",
  "background.accent.gray.subtlest": "background-accent-gray-subtlest",
  "background-accent-gray-subtlest": "background-accent-gray-subtlest",
  "background.accent.gray.subtler": "background-accent-gray-subtler",
  "background-accent-gray-subtler": "background-accent-gray-subtler",
  "background.accent.gray.subtle": "background-accent-gray-subtle",
  "background-accent-gray-subtle": "background-accent-gray-subtle",
  "background.accent.gray.bolder": "background-accent-gray-bolder",
  "background-accent-gray-bolder": "background-accent-gray-bolder",
  "background.accent.lime.subtlest": "background-accent-lime-subtlest",
  "background-accent-lime-subtlest": "background-accent-lime-subtlest",
  "background.accent.lime.subtler": "background-accent-lime-subtler",
  "background-accent-lime-subtler": "background-accent-lime-subtler",
  "background.accent.lime.subtle": "background-accent-lime-subtle",
  "background-accent-lime-subtle": "background-accent-lime-subtle",
  "background.accent.lime.bolder": "background-accent-lime-bolder",
  "background-accent-lime-bolder": "background-accent-lime-bolder",
  "background.input.default": "background-input-default",
  "background-input-default": "background-input-default",
  "background.input.hovered": "background-input-hovered",
  "background-input-hovered": "background-input-hovered",
  "background.input.pressed": "background-input-pressed",
  "background-input-pressed": "background-input-pressed",
  "background.inverse.subtle.default": "background-inverse-subtle-default",
  "background-inverse-subtle-default": "background-inverse-subtle-default",
  "background.inverse.subtle.hovered": "background-inverse-subtle-hovered",
  "background-inverse-subtle-hovered": "background-inverse-subtle-hovered",
  "background.inverse.subtle.pressed": "background-inverse-subtle-pressed",
  "background-inverse-subtle-pressed": "background-inverse-subtle-pressed",
  "background.brand.subtlest.default": "background-brand-subtlest-default",
  "background-brand-subtlest-default": "background-brand-subtlest-default",
  "background.brand.subtlest.hovered": "background-brand-subtlest-hovered",
  "background-brand-subtlest-hovered": "background-brand-subtlest-hovered",
  "background.brand.subtlest.pressed": "background-brand-subtlest-pressed",
  "background-brand-subtlest-pressed": "background-brand-subtlest-pressed",
  "background.brand.bold.default": "background-brand-bold-default",
  "background-brand-bold-default": "background-brand-bold-default",
  "background.brand.bold.hovered": "background-brand-bold-hovered",
  "background-brand-bold-hovered": "background-brand-bold-hovered",
  "background.brand.bold.pressed": "background-brand-bold-pressed",
  "background-brand-bold-pressed": "background-brand-bold-pressed",
  "background.brand.boldest.default": "background-brand-boldest-default",
  "background-brand-boldest-default": "background-brand-boldest-default",
  "background.brand.boldest.hovered": "background-brand-boldest-hovered",
  "background-brand-boldest-hovered": "background-brand-boldest-hovered",
  "background.brand.boldest.pressed": "background-brand-boldest-pressed",
  "background-brand-boldest-pressed": "background-brand-boldest-pressed",
  "background.neutral.default.default": "background-neutral-default-default",
  "background-neutral-default-default": "background-neutral-default-default",
  "background.neutral.default.hovered": "background-neutral-default-hovered",
  "background-neutral-default-hovered": "background-neutral-default-hovered",
  "background.neutral.default.pressed": "background-neutral-default-pressed",
  "background-neutral-default-pressed": "background-neutral-default-pressed",
  "background.neutral.subtle.default": "background-neutral-subtle-default",
  "background-neutral-subtle-default": "background-neutral-subtle-default",
  "background.neutral.subtle.hovered": "background-neutral-subtle-hovered",
  "background-neutral-subtle-hovered": "background-neutral-subtle-hovered",
  "background.neutral.subtle.pressed": "background-neutral-subtle-pressed",
  "background-neutral-subtle-pressed": "background-neutral-subtle-pressed",
  "background.neutral.bold.default": "background-neutral-bold-default",
  "background-neutral-bold-default": "background-neutral-bold-default",
  "background.neutral.bold.hovered": "background-neutral-bold-hovered",
  "background-neutral-bold-hovered": "background-neutral-bold-hovered",
  "background.neutral.bold.pressed": "background-neutral-bold-pressed",
  "background-neutral-bold-pressed": "background-neutral-bold-pressed",
  "background.selected.default.default": "background-selected-default-default",
  "background-selected-default-default": "background-selected-default-default",
  "background.selected.default.hovered": "background-selected-default-hovered",
  "background-selected-default-hovered": "background-selected-default-hovered",
  "background.selected.default.pressed": "background-selected-default-pressed",
  "background-selected-default-pressed": "background-selected-default-pressed",
  "background.selected.bold.default": "background-selected-bold-default",
  "background-selected-bold-default": "background-selected-bold-default",
  "background.selected.bold.hovered": "background-selected-bold-hovered",
  "background-selected-bold-hovered": "background-selected-bold-hovered",
  "background.selected.bold.pressed": "background-selected-bold-pressed",
  "background-selected-bold-pressed": "background-selected-bold-pressed",
  "background.disabled": "background-disabled",
  "background-disabled": "background-disabled",
  "background.information.default.default":
    "background-information-default-default",
  "background-information-default-default":
    "background-information-default-default",
  "background.information.default.hovered":
    "background-information-default-hovered",
  "background-information-default-hovered":
    "background-information-default-hovered",
  "background.information.default.pressed":
    "background-information-default-pressed",
  "background-information-default-pressed":
    "background-information-default-pressed",
  "background.information.bold.default": "background-information-bold-default",
  "background-information-bold-default": "background-information-bold-default",
  "background.information.bold.hovered": "background-information-bold-hovered",
  "background-information-bold-hovered": "background-information-bold-hovered",
  "background.information.bold.pressed": "background-information-bold-pressed",
  "background-information-bold-pressed": "background-information-bold-pressed",
  "background.danger.default.default": "background-danger-default-default",
  "background-danger-default-default": "background-danger-default-default",
  "background.danger.default.hovered": "background-danger-default-hovered",
  "background-danger-default-hovered": "background-danger-default-hovered",
  "background.danger.default.pressed": "background-danger-default-pressed",
  "background-danger-default-pressed": "background-danger-default-pressed",
  "background.danger.bold.default": "background-danger-bold-default",
  "background-danger-bold-default": "background-danger-bold-default",
  "background.danger.bold.hovered": "background-danger-bold-hovered",
  "background-danger-bold-hovered": "background-danger-bold-hovered",
  "background.danger.bold.pressed": "background-danger-bold-pressed",
  "background-danger-bold-pressed": "background-danger-bold-pressed",
  "background.success.default.default": "background-success-default-default",
  "background-success-default-default": "background-success-default-default",
  "background.success.default.hovered": "background-success-default-hovered",
  "background-success-default-hovered": "background-success-default-hovered",
  "background.success.default.pressed": "background-success-default-pressed",
  "background-success-default-pressed": "background-success-default-pressed",
  "background.success.bold.default": "background-success-bold-default",
  "background-success-bold-default": "background-success-bold-default",
  "background.success.bold.hovered": "background-success-bold-hovered",
  "background-success-bold-hovered": "background-success-bold-hovered",
  "background.success.bold.pressed": "background-success-bold-pressed",
  "background-success-bold-pressed": "background-success-bold-pressed",
  "background.discovery.default.default":
    "background-discovery-default-default",
  "background-discovery-default-default":
    "background-discovery-default-default",
  "background.discovery.default.hovered":
    "background-discovery-default-hovered",
  "background-discovery-default-hovered":
    "background-discovery-default-hovered",
  "background.discovery.default.pressed":
    "background-discovery-default-pressed",
  "background-discovery-default-pressed":
    "background-discovery-default-pressed",
  "background.discovery.bold.default": "background-discovery-bold-default",
  "background-discovery-bold-default": "background-discovery-bold-default",
  "background.discovery.bold.hovered": "background-discovery-bold-hovered",
  "background-discovery-bold-hovered": "background-discovery-bold-hovered",
  "background.discovery.bold.pressed": "background-discovery-bold-pressed",
  "background-discovery-bold-pressed": "background-discovery-bold-pressed",
  "background.warning.default.default": "background-warning-default-default",
  "background-warning-default-default": "background-warning-default-default",
  "background.warning.default.hovered": "background-warning-default-hovered",
  "background-warning-default-hovered": "background-warning-default-hovered",
  "background.warning.default.pressed": "background-warning-default-pressed",
  "background-warning-default-pressed": "background-warning-default-pressed",
  "background.warning.bold.default": "background-warning-bold-default",
  "background-warning-bold-default": "background-warning-bold-default",
  "background.warning.bold.hovered": "background-warning-bold-hovered",
  "background-warning-bold-hovered": "background-warning-bold-hovered",
  "background.warning.bold.pressed": "background-warning-bold-pressed",
  "background-warning-bold-pressed": "background-warning-bold-pressed",
  "blanket.default": "blanket-default",
  "blanket-default": "blanket-default",
  "blanket.selected": "blanket-selected",
  "blanket-selected": "blanket-selected",
  "blanket.danger": "blanket-danger",
  "blanket-danger": "blanket-danger",
  "text.default": "text-default",
  "text-default": "text-default",
  "text.subtle": "text-subtle",
  "text-subtle": "text-subtle",
  "text.subtlest": "text-subtlest",
  "text-subtlest": "text-subtlest",
  "text.disabled": "text-disabled",
  "text-disabled": "text-disabled",
  "text.selected": "text-selected",
  "text-selected": "text-selected",
  "text.inverse": "text-inverse",
  "text-inverse": "text-inverse",
  "text.success": "text-success",
  "text-success": "text-success",
  "text.danger": "text-danger",
  "text-danger": "text-danger",
  "text.information": "text-information",
  "text-information": "text-information",
  "text.warning.default": "text-warning-default",
  "text-warning-default": "text-warning-default",
  "text.warning.inverse": "text-warning-inverse",
  "text-warning-inverse": "text-warning-inverse",
  "text.discovery": "text-discovery",
  "text-discovery": "text-discovery",
  "text.brand": "text-brand",
  "text-brand": "text-brand",
  "text.accent.blue.default": "text-accent-blue-default",
  "text-accent-blue-default": "text-accent-blue-default",
  "text.accent.blue.bolder": "text-accent-blue-bolder",
  "text-accent-blue-bolder": "text-accent-blue-bolder",
  "text.accent.red.default": "text-accent-red-default",
  "text-accent-red-default": "text-accent-red-default",
  "text.accent.red.bolder": "text-accent-red-bolder",
  "text-accent-red-bolder": "text-accent-red-bolder",
  "text.accent.orange.default": "text-accent-orange-default",
  "text-accent-orange-default": "text-accent-orange-default",
  "text.accent.orange.bolder": "text-accent-orange-bolder",
  "text-accent-orange-bolder": "text-accent-orange-bolder",
  "text.accent.yellow.default": "text-accent-yellow-default",
  "text-accent-yellow-default": "text-accent-yellow-default",
  "text.accent.yellow.bolder": "text-accent-yellow-bolder",
  "text-accent-yellow-bolder": "text-accent-yellow-bolder",
  "text.accent.green.default": "text-accent-green-default",
  "text-accent-green-default": "text-accent-green-default",
  "text.accent.green.bolder": "text-accent-green-bolder",
  "text-accent-green-bolder": "text-accent-green-bolder",
  "text.accent.purple.default": "text-accent-purple-default",
  "text-accent-purple-default": "text-accent-purple-default",
  "text.accent.purple.bolder": "text-accent-purple-bolder",
  "text-accent-purple-bolder": "text-accent-purple-bolder",
  "text.accent.teal.default": "text-accent-teal-default",
  "text-accent-teal-default": "text-accent-teal-default",
  "text.accent.teal.bolder": "text-accent-teal-bolder",
  "text-accent-teal-bolder": "text-accent-teal-bolder",
  "text.accent.magenta.default": "text-accent-magenta-default",
  "text-accent-magenta-default": "text-accent-magenta-default",
  "text.accent.magenta.bolder": "text-accent-magenta-bolder",
  "text-accent-magenta-bolder": "text-accent-magenta-bolder",
  "text.accent.gray.default": "text-accent-gray-default",
  "text-accent-gray-default": "text-accent-gray-default",
  "text.accent.gray.bolder": "text-accent-gray-bolder",
  "text-accent-gray-bolder": "text-accent-gray-bolder",
  "text.accent.lime.default": "text-accent-lime-default",
  "text-accent-lime-default": "text-accent-lime-default",
  "text.accent.lime.bolder": "text-accent-lime-bolder",
  "text-accent-lime-bolder": "text-accent-lime-bolder",
  "link.default": "link-default",
  "link-default": "link-default",
  "link.hovered": "link-hovered",
  "link-hovered": "link-hovered",
  "link.pressed": "link-pressed",
  "link-pressed": "link-pressed",
  "link.visited": "link-visited",
  "link-visited": "link-visited",
  "icon.accent.blue": "icon-accent-blue",
  "icon-accent-blue": "icon-accent-blue",
  "icon.accent.red": "icon-accent-red",
  "icon-accent-red": "icon-accent-red",
  "icon.accent.orange": "icon-accent-orange",
  "icon-accent-orange": "icon-accent-orange",
  "icon.accent.yellow": "icon-accent-yellow",
  "icon-accent-yellow": "icon-accent-yellow",
  "icon.accent.green": "icon-accent-green",
  "icon-accent-green": "icon-accent-green",
  "icon.accent.purple": "icon-accent-purple",
  "icon-accent-purple": "icon-accent-purple",
  "icon.accent.teal": "icon-accent-teal",
  "icon-accent-teal": "icon-accent-teal",
  "icon.accent.magenta": "icon-accent-magenta",
  "icon-accent-magenta": "icon-accent-magenta",
  "icon.accent.gray": "icon-accent-gray",
  "icon-accent-gray": "icon-accent-gray",
  "icon.accent.lime": "icon-accent-lime",
  "icon-accent-lime": "icon-accent-lime",
  "icon.default": "icon-default",
  "icon-default": "icon-default",
  "icon.subtle": "icon-subtle",
  "icon-subtle": "icon-subtle",
  "icon.inverse": "icon-inverse",
  "icon-inverse": "icon-inverse",
  "icon.disabled": "icon-disabled",
  "icon-disabled": "icon-disabled",
  "icon.brand": "icon-brand",
  "icon-brand": "icon-brand",
  "icon.selected": "icon-selected",
  "icon-selected": "icon-selected",
  "icon.danger": "icon-danger",
  "icon-danger": "icon-danger",
  "icon.success": "icon-success",
  "icon-success": "icon-success",
  "icon.discovery": "icon-discovery",
  "icon-discovery": "icon-discovery",
  "icon.information": "icon-information",
  "icon-information": "icon-information",
  "icon.warning.default": "icon-warning-default",
  "icon-warning-default": "icon-warning-default",
  "icon.warning.inverse": "icon-warning-inverse",
  "icon-warning-inverse": "icon-warning-inverse",
  "interaction.hovered": "interaction-hovered",
  "interaction-hovered": "interaction-hovered",
  "interaction.pressed": "interaction-pressed",
  "interaction-pressed": "interaction-pressed",
  "skeleton.default": "skeleton-default",
  "skeleton-default": "skeleton-default",
  "skeleton.subtle": "skeleton-subtle",
  "skeleton-subtle": "skeleton-subtle",
  "chart.brand.default": "chart-brand-default",
  "chart-brand-default": "chart-brand-default",
  "chart.brand.hovered": "chart-brand-hovered",
  "chart-brand-hovered": "chart-brand-hovered",
  "chart.neutral.default": "chart-neutral-default",
  "chart-neutral-default": "chart-neutral-default",
  "chart.neutral.hovered": "chart-neutral-hovered",
  "chart-neutral-hovered": "chart-neutral-hovered",
  "chart.success.default.default": "chart-success-default-default",
  "chart-success-default-default": "chart-success-default-default",
  "chart.success.default.hovered": "chart-success-default-hovered",
  "chart-success-default-hovered": "chart-success-default-hovered",
  "chart.success.bold.default": "chart-success-bold-default",
  "chart-success-bold-default": "chart-success-bold-default",
  "chart.success.bold.hovered": "chart-success-bold-hovered",
  "chart-success-bold-hovered": "chart-success-bold-hovered",
  "chart.danger.default.default": "chart-danger-default-default",
  "chart-danger-default-default": "chart-danger-default-default",
  "chart.danger.default.hovered": "chart-danger-default-hovered",
  "chart-danger-default-hovered": "chart-danger-default-hovered",
  "chart.danger.bold.default": "chart-danger-bold-default",
  "chart-danger-bold-default": "chart-danger-bold-default",
  "chart.danger.bold.hovered": "chart-danger-bold-hovered",
  "chart-danger-bold-hovered": "chart-danger-bold-hovered",
  "chart.warning.default.default": "chart-warning-default-default",
  "chart-warning-default-default": "chart-warning-default-default",
  "chart.warning.default.hovered": "chart-warning-default-hovered",
  "chart-warning-default-hovered": "chart-warning-default-hovered",
  "chart.warning.bold.default": "chart-warning-bold-default",
  "chart-warning-bold-default": "chart-warning-bold-default",
  "chart.warning.bold.hovered": "chart-warning-bold-hovered",
  "chart-warning-bold-hovered": "chart-warning-bold-hovered",
  "chart.information.default.default": "chart-information-default-default",
  "chart-information-default-default": "chart-information-default-default",
  "chart.information.default.hovered": "chart-information-default-hovered",
  "chart-information-default-hovered": "chart-information-default-hovered",
  "chart.information.bold.default": "chart-information-bold-default",
  "chart-information-bold-default": "chart-information-bold-default",
  "chart.information.bold.hovered": "chart-information-bold-hovered",
  "chart-information-bold-hovered": "chart-information-bold-hovered",
  "chart.discovery.default.default": "chart-discovery-default-default",
  "chart-discovery-default-default": "chart-discovery-default-default",
  "chart.discovery.default.hovered": "chart-discovery-default-hovered",
  "chart-discovery-default-hovered": "chart-discovery-default-hovered",
  "chart.discovery.bold.default": "chart-discovery-bold-default",
  "chart-discovery-bold-default": "chart-discovery-bold-default",
  "chart.discovery.bold.hovered": "chart-discovery-bold-hovered",
  "chart-discovery-bold-hovered": "chart-discovery-bold-hovered",
  "chart.categorical.1.default": "chart-categorical-1-default",
  "chart-categorical-1-default": "chart-categorical-1-default",
  "chart.categorical.1.hovered": "chart-categorical-1-hovered",
  "chart-categorical-1-hovered": "chart-categorical-1-hovered",
  "chart.categorical.2.default": "chart-categorical-2-default",
  "chart-categorical-2-default": "chart-categorical-2-default",
  "chart.categorical.2.hovered": "chart-categorical-2-hovered",
  "chart-categorical-2-hovered": "chart-categorical-2-hovered",
  "chart.categorical.3.default": "chart-categorical-3-default",
  "chart-categorical-3-default": "chart-categorical-3-default",
  "chart.categorical.3.hovered": "chart-categorical-3-hovered",
  "chart-categorical-3-hovered": "chart-categorical-3-hovered",
  "chart.categorical.4.default": "chart-categorical-4-default",
  "chart-categorical-4-default": "chart-categorical-4-default",
  "chart.categorical.4.hovered": "chart-categorical-4-hovered",
  "chart-categorical-4-hovered": "chart-categorical-4-hovered",
  "chart.categorical.5.default": "chart-categorical-5-default",
  "chart-categorical-5-default": "chart-categorical-5-default",
  "chart.categorical.5.hovered": "chart-categorical-5-hovered",
  "chart-categorical-5-hovered": "chart-categorical-5-hovered",
  "chart.categorical.6.default": "chart-categorical-6-default",
  "chart-categorical-6-default": "chart-categorical-6-default",
  "chart.categorical.6.hovered": "chart-categorical-6-hovered",
  "chart-categorical-6-hovered": "chart-categorical-6-hovered",
  "chart.categorical.7.default": "chart-categorical-7-default",
  "chart-categorical-7-default": "chart-categorical-7-default",
  "chart.categorical.7.hovered": "chart-categorical-7-hovered",
  "chart-categorical-7-hovered": "chart-categorical-7-hovered",
  "chart.categorical.8.default": "chart-categorical-8-default",
  "chart-categorical-8-default": "chart-categorical-8-default",
  "chart.categorical.8.hovered": "chart-categorical-8-hovered",
  "chart-categorical-8-hovered": "chart-categorical-8-hovered",
  "chart.blue.bold.default": "chart-blue-bold-default",
  "chart-blue-bold-default": "chart-blue-bold-default",
  "chart.blue.bold.hovered": "chart-blue-bold-hovered",
  "chart-blue-bold-hovered": "chart-blue-bold-hovered",
  "chart.blue.bolder.default": "chart-blue-bolder-default",
  "chart-blue-bolder-default": "chart-blue-bolder-default",
  "chart.blue.bolder.hovered": "chart-blue-bolder-hovered",
  "chart-blue-bolder-hovered": "chart-blue-bolder-hovered",
  "chart.blue.boldest.default": "chart-blue-boldest-default",
  "chart-blue-boldest-default": "chart-blue-boldest-default",
  "chart.blue.boldest.hovered": "chart-blue-boldest-hovered",
  "chart-blue-boldest-hovered": "chart-blue-boldest-hovered",
  "chart.red.bold.default": "chart-red-bold-default",
  "chart-red-bold-default": "chart-red-bold-default",
  "chart.red.bold.hovered": "chart-red-bold-hovered",
  "chart-red-bold-hovered": "chart-red-bold-hovered",
  "chart.red.bolder.default": "chart-red-bolder-default",
  "chart-red-bolder-default": "chart-red-bolder-default",
  "chart.red.bolder.hovered": "chart-red-bolder-hovered",
  "chart-red-bolder-hovered": "chart-red-bolder-hovered",
  "chart.red.boldest.default": "chart-red-boldest-default",
  "chart-red-boldest-default": "chart-red-boldest-default",
  "chart.red.boldest.hovered": "chart-red-boldest-hovered",
  "chart-red-boldest-hovered": "chart-red-boldest-hovered",
  "chart.orange.bold.default": "chart-orange-bold-default",
  "chart-orange-bold-default": "chart-orange-bold-default",
  "chart.orange.bold.hovered": "chart-orange-bold-hovered",
  "chart-orange-bold-hovered": "chart-orange-bold-hovered",
  "chart.orange.bolder.default": "chart-orange-bolder-default",
  "chart-orange-bolder-default": "chart-orange-bolder-default",
  "chart.orange.bolder.hovered": "chart-orange-bolder-hovered",
  "chart-orange-bolder-hovered": "chart-orange-bolder-hovered",
  "chart.orange.boldest.default": "chart-orange-boldest-default",
  "chart-orange-boldest-default": "chart-orange-boldest-default",
  "chart.orange.boldest.hovered": "chart-orange-boldest-hovered",
  "chart-orange-boldest-hovered": "chart-orange-boldest-hovered",
  "chart.yellow.bold.default": "chart-yellow-bold-default",
  "chart-yellow-bold-default": "chart-yellow-bold-default",
  "chart.yellow.bold.hovered": "chart-yellow-bold-hovered",
  "chart-yellow-bold-hovered": "chart-yellow-bold-hovered",
  "chart.yellow.bolder.default": "chart-yellow-bolder-default",
  "chart-yellow-bolder-default": "chart-yellow-bolder-default",
  "chart.yellow.bolder.hovered": "chart-yellow-bolder-hovered",
  "chart-yellow-bolder-hovered": "chart-yellow-bolder-hovered",
  "chart.yellow.boldest.default": "chart-yellow-boldest-default",
  "chart-yellow-boldest-default": "chart-yellow-boldest-default",
  "chart.yellow.boldest.hovered": "chart-yellow-boldest-hovered",
  "chart-yellow-boldest-hovered": "chart-yellow-boldest-hovered",
  "chart.green.bold.default": "chart-green-bold-default",
  "chart-green-bold-default": "chart-green-bold-default",
  "chart.green.bold.hovered": "chart-green-bold-hovered",
  "chart-green-bold-hovered": "chart-green-bold-hovered",
  "chart.green.bolder.default": "chart-green-bolder-default",
  "chart-green-bolder-default": "chart-green-bolder-default",
  "chart.green.bolder.hovered": "chart-green-bolder-hovered",
  "chart-green-bolder-hovered": "chart-green-bolder-hovered",
  "chart.green.boldest.default": "chart-green-boldest-default",
  "chart-green-boldest-default": "chart-green-boldest-default",
  "chart.green.boldest.hovered": "chart-green-boldest-hovered",
  "chart-green-boldest-hovered": "chart-green-boldest-hovered",
  "chart.teal.bold.default": "chart-teal-bold-default",
  "chart-teal-bold-default": "chart-teal-bold-default",
  "chart.teal.bold.hovered": "chart-teal-bold-hovered",
  "chart-teal-bold-hovered": "chart-teal-bold-hovered",
  "chart.teal.bolder.default": "chart-teal-bolder-default",
  "chart-teal-bolder-default": "chart-teal-bolder-default",
  "chart.teal.bolder.hovered": "chart-teal-bolder-hovered",
  "chart-teal-bolder-hovered": "chart-teal-bolder-hovered",
  "chart.teal.boldest.default": "chart-teal-boldest-default",
  "chart-teal-boldest-default": "chart-teal-boldest-default",
  "chart.teal.boldest.hovered": "chart-teal-boldest-hovered",
  "chart-teal-boldest-hovered": "chart-teal-boldest-hovered",
  "chart.purple.bold.default": "chart-purple-bold-default",
  "chart-purple-bold-default": "chart-purple-bold-default",
  "chart.purple.bold.hovered": "chart-purple-bold-hovered",
  "chart-purple-bold-hovered": "chart-purple-bold-hovered",
  "chart.purple.bolder.default": "chart-purple-bolder-default",
  "chart-purple-bolder-default": "chart-purple-bolder-default",
  "chart.purple.bolder.hovered": "chart-purple-bolder-hovered",
  "chart-purple-bolder-hovered": "chart-purple-bolder-hovered",
  "chart.purple.boldest.default": "chart-purple-boldest-default",
  "chart-purple-boldest-default": "chart-purple-boldest-default",
  "chart.purple.boldest.hovered": "chart-purple-boldest-hovered",
  "chart-purple-boldest-hovered": "chart-purple-boldest-hovered",
  "chart.magenta.bold.default": "chart-magenta-bold-default",
  "chart-magenta-bold-default": "chart-magenta-bold-default",
  "chart.magenta.bold.hovered": "chart-magenta-bold-hovered",
  "chart-magenta-bold-hovered": "chart-magenta-bold-hovered",
  "chart.magenta.bolder.default": "chart-magenta-bolder-default",
  "chart-magenta-bolder-default": "chart-magenta-bolder-default",
  "chart.magenta.bolder.hovered": "chart-magenta-bolder-hovered",
  "chart-magenta-bolder-hovered": "chart-magenta-bolder-hovered",
  "chart.magenta.boldest.default": "chart-magenta-boldest-default",
  "chart-magenta-boldest-default": "chart-magenta-boldest-default",
  "chart.magenta.boldest.hovered": "chart-magenta-boldest-hovered",
  "chart-magenta-boldest-hovered": "chart-magenta-boldest-hovered",
  "chart.gray.bold.default": "chart-gray-bold-default",
  "chart-gray-bold-default": "chart-gray-bold-default",
  "chart.gray.bold.hovered": "chart-gray-bold-hovered",
  "chart-gray-bold-hovered": "chart-gray-bold-hovered",
  "chart.gray.bolder.default": "chart-gray-bolder-default",
  "chart-gray-bolder-default": "chart-gray-bolder-default",
  "chart.gray.bolder.hovered": "chart-gray-bolder-hovered",
  "chart-gray-bolder-hovered": "chart-gray-bolder-hovered",
  "chart.gray.boldest.default": "chart-gray-boldest-default",
  "chart-gray-boldest-default": "chart-gray-boldest-default",
  "chart.gray.boldest.hovered": "chart-gray-boldest-hovered",
  "chart-gray-boldest-hovered": "chart-gray-boldest-hovered",
  "chart.lime.bold.default": "chart-lime-bold-default",
  "chart-lime-bold-default": "chart-lime-bold-default",
  "chart.lime.bold.hovered": "chart-lime-bold-hovered",
  "chart-lime-bold-hovered": "chart-lime-bold-hovered",
  "chart.lime.bolder.default": "chart-lime-bolder-default",
  "chart-lime-bolder-default": "chart-lime-bolder-default",
  "chart.lime.bolder.hovered": "chart-lime-bolder-hovered",
  "chart-lime-bolder-hovered": "chart-lime-bolder-hovered",
  "chart.lime.boldest.default": "chart-lime-boldest-default",
  "chart-lime-boldest-default": "chart-lime-boldest-default",
  "chart.lime.boldest.hovered": "chart-lime-boldest-hovered",
  "chart-lime-boldest-hovered": "chart-lime-boldest-hovered",
};

const scaleTokensObject: Record<string, string> = {
  "scale.gray.100": "scale-gray-100",
  "scale-gray-100": "scale-gray-100",
  "scale.gray.200": "scale-gray-200",
  "scale-gray-200": "scale-gray-200",
  "scale.gray.300": "scale-gray-300",
  "scale-gray-300": "scale-gray-300",
  "scale.gray.400": "scale-gray-400",
  "scale-gray-400": "scale-gray-400",
  "scale.gray.500": "scale-gray-500",
  "scale-gray-500": "scale-gray-500",
  "scale.gray.600": "scale-gray-600",
  "scale-gray-600": "scale-gray-600",
  "scale.gray.700": "scale-gray-700",
  "scale-gray-700": "scale-gray-700",
  "scale.gray.800": "scale-gray-800",
  "scale-gray-800": "scale-gray-800",
  "scale.gray.900": "scale-gray-900",
  "scale-gray-900": "scale-gray-900",
  "scale.gray.000": "scale-gray-000",
  "scale-gray-000": "scale-gray-000",
  "scale.neutral.100": "scale-neutral-100",
  "scale-neutral-100": "scale-neutral-100",
  "scale.neutral.200": "scale-neutral-200",
  "scale-neutral-200": "scale-neutral-200",
  "scale.neutral.250": "scale-neutral-250",
  "scale-neutral-250": "scale-neutral-250",
  "scale.neutral.300": "scale-neutral-300",
  "scale-neutral-300": "scale-neutral-300",
  "scale.neutral.350": "scale-neutral-350",
  "scale-neutral-350": "scale-neutral-350",
  "scale.neutral.400": "scale-neutral-400",
  "scale-neutral-400": "scale-neutral-400",
  "scale.neutral.500": "scale-neutral-500",
  "scale-neutral-500": "scale-neutral-500",
  "scale.neutral.600": "scale-neutral-600",
  "scale-neutral-600": "scale-neutral-600",
  "scale.neutral.700": "scale-neutral-700",
  "scale-neutral-700": "scale-neutral-700",
  "scale.neutral.800": "scale-neutral-800",
  "scale-neutral-800": "scale-neutral-800",
  "scale.neutral.900": "scale-neutral-900",
  "scale-neutral-900": "scale-neutral-900",
  "scale.neutral.1000": "scale-neutral-1000",
  "scale-neutral-1000": "scale-neutral-1000",
  "scale.neutral.1100": "scale-neutral-1100",
  "scale-neutral-1100": "scale-neutral-1100",
  "scale.neutral.000": "scale-neutral-000",
  "scale-neutral-000": "scale-neutral-000",
  "scale.neutralAlpha.100": "scale-neutralAlpha-100",
  "scale-neutralAlpha-100": "scale-neutralAlpha-100",
  "scale.neutralAlpha.200": "scale-neutralAlpha-200",
  "scale-neutralAlpha-200": "scale-neutralAlpha-200",
  "scale.neutralAlpha.250": "scale-neutralAlpha-250",
  "scale-neutralAlpha-250": "scale-neutralAlpha-250",
  "scale.neutralAlpha.300": "scale-neutralAlpha-300",
  "scale-neutralAlpha-300": "scale-neutralAlpha-300",
  "scale.neutralAlpha.350": "scale-neutralAlpha-350",
  "scale-neutralAlpha-350": "scale-neutralAlpha-350",
  "scale.neutralAlpha.400": "scale-neutralAlpha-400",
  "scale-neutralAlpha-400": "scale-neutralAlpha-400",
  "scale.neutralAlpha.500": "scale-neutralAlpha-500",
  "scale-neutralAlpha-500": "scale-neutralAlpha-500",
  "scale.neutralAlpha.600": "scale-neutralAlpha-600",
  "scale-neutralAlpha-600": "scale-neutralAlpha-600",
  "scale.neutralAlpha.700": "scale-neutralAlpha-700",
  "scale-neutralAlpha-700": "scale-neutralAlpha-700",
  "scale.neutralAlpha.800": "scale-neutralAlpha-800",
  "scale-neutralAlpha-800": "scale-neutralAlpha-800",
  "scale.neutralAlpha.900": "scale-neutralAlpha-900",
  "scale-neutralAlpha-900": "scale-neutralAlpha-900",
  "scale.neutralAlpha.000": "scale-neutralAlpha-000",
  "scale-neutralAlpha-000": "scale-neutralAlpha-000",
  "scale.blue.100": "scale-blue-100",
  "scale-blue-100": "scale-blue-100",
  "scale.blue.200": "scale-blue-200",
  "scale-blue-200": "scale-blue-200",
  "scale.blue.300": "scale-blue-300",
  "scale-blue-300": "scale-blue-300",
  "scale.blue.400": "scale-blue-400",
  "scale-blue-400": "scale-blue-400",
  "scale.blue.500": "scale-blue-500",
  "scale-blue-500": "scale-blue-500",
  "scale.blue.600": "scale-blue-600",
  "scale-blue-600": "scale-blue-600",
  "scale.blue.700": "scale-blue-700",
  "scale-blue-700": "scale-blue-700",
  "scale.blue.800": "scale-blue-800",
  "scale-blue-800": "scale-blue-800",
  "scale.blue.900": "scale-blue-900",
  "scale-blue-900": "scale-blue-900",
  "scale.blue.000": "scale-blue-000",
  "scale-blue-000": "scale-blue-000",
  "scale.teal.100": "scale-teal-100",
  "scale-teal-100": "scale-teal-100",
  "scale.teal.200": "scale-teal-200",
  "scale-teal-200": "scale-teal-200",
  "scale.teal.300": "scale-teal-300",
  "scale-teal-300": "scale-teal-300",
  "scale.teal.400": "scale-teal-400",
  "scale-teal-400": "scale-teal-400",
  "scale.teal.500": "scale-teal-500",
  "scale-teal-500": "scale-teal-500",
  "scale.teal.600": "scale-teal-600",
  "scale-teal-600": "scale-teal-600",
  "scale.teal.700": "scale-teal-700",
  "scale-teal-700": "scale-teal-700",
  "scale.teal.800": "scale-teal-800",
  "scale-teal-800": "scale-teal-800",
  "scale.teal.900": "scale-teal-900",
  "scale-teal-900": "scale-teal-900",
  "scale.teal.000": "scale-teal-000",
  "scale-teal-000": "scale-teal-000",
  "scale.purple.100": "scale-purple-100",
  "scale-purple-100": "scale-purple-100",
  "scale.purple.200": "scale-purple-200",
  "scale-purple-200": "scale-purple-200",
  "scale.purple.300": "scale-purple-300",
  "scale-purple-300": "scale-purple-300",
  "scale.purple.400": "scale-purple-400",
  "scale-purple-400": "scale-purple-400",
  "scale.purple.500": "scale-purple-500",
  "scale-purple-500": "scale-purple-500",
  "scale.purple.600": "scale-purple-600",
  "scale-purple-600": "scale-purple-600",
  "scale.purple.700": "scale-purple-700",
  "scale-purple-700": "scale-purple-700",
  "scale.purple.800": "scale-purple-800",
  "scale-purple-800": "scale-purple-800",
  "scale.purple.900": "scale-purple-900",
  "scale-purple-900": "scale-purple-900",
  "scale.purple.000": "scale-purple-000",
  "scale-purple-000": "scale-purple-000",
  "scale.green.100": "scale-green-100",
  "scale-green-100": "scale-green-100",
  "scale.green.200": "scale-green-200",
  "scale-green-200": "scale-green-200",
  "scale.green.300": "scale-green-300",
  "scale-green-300": "scale-green-300",
  "scale.green.400": "scale-green-400",
  "scale-green-400": "scale-green-400",
  "scale.green.500": "scale-green-500",
  "scale-green-500": "scale-green-500",
  "scale.green.600": "scale-green-600",
  "scale-green-600": "scale-green-600",
  "scale.green.700": "scale-green-700",
  "scale-green-700": "scale-green-700",
  "scale.green.800": "scale-green-800",
  "scale-green-800": "scale-green-800",
  "scale.green.900": "scale-green-900",
  "scale-green-900": "scale-green-900",
  "scale.green.000": "scale-green-000",
  "scale-green-000": "scale-green-000",
  "scale.yellow.100": "scale-yellow-100",
  "scale-yellow-100": "scale-yellow-100",
  "scale.yellow.200": "scale-yellow-200",
  "scale-yellow-200": "scale-yellow-200",
  "scale.yellow.300": "scale-yellow-300",
  "scale-yellow-300": "scale-yellow-300",
  "scale.yellow.400": "scale-yellow-400",
  "scale-yellow-400": "scale-yellow-400",
  "scale.yellow.500": "scale-yellow-500",
  "scale-yellow-500": "scale-yellow-500",
  "scale.yellow.600": "scale-yellow-600",
  "scale-yellow-600": "scale-yellow-600",
  "scale.yellow.700": "scale-yellow-700",
  "scale-yellow-700": "scale-yellow-700",
  "scale.yellow.800": "scale-yellow-800",
  "scale-yellow-800": "scale-yellow-800",
  "scale.yellow.900": "scale-yellow-900",
  "scale-yellow-900": "scale-yellow-900",
  "scale.yellow.000": "scale-yellow-000",
  "scale-yellow-000": "scale-yellow-000",
  "scale.red.100": "scale-red-100",
  "scale-red-100": "scale-red-100",
  "scale.red.200": "scale-red-200",
  "scale-red-200": "scale-red-200",
  "scale.red.300": "scale-red-300",
  "scale-red-300": "scale-red-300",
  "scale.red.400": "scale-red-400",
  "scale-red-400": "scale-red-400",
  "scale.red.500": "scale-red-500",
  "scale-red-500": "scale-red-500",
  "scale.red.600": "scale-red-600",
  "scale-red-600": "scale-red-600",
  "scale.red.700": "scale-red-700",
  "scale-red-700": "scale-red-700",
  "scale.red.800": "scale-red-800",
  "scale-red-800": "scale-red-800",
  "scale.red.900": "scale-red-900",
  "scale-red-900": "scale-red-900",
  "scale.red.000": "scale-red-000",
  "scale-red-000": "scale-red-000",
  "scale.orange.100": "scale-orange-100",
  "scale-orange-100": "scale-orange-100",
  "scale.orange.200": "scale-orange-200",
  "scale-orange-200": "scale-orange-200",
  "scale.orange.300": "scale-orange-300",
  "scale-orange-300": "scale-orange-300",
  "scale.orange.400": "scale-orange-400",
  "scale-orange-400": "scale-orange-400",
  "scale.orange.500": "scale-orange-500",
  "scale-orange-500": "scale-orange-500",
  "scale.orange.600": "scale-orange-600",
  "scale-orange-600": "scale-orange-600",
  "scale.orange.700": "scale-orange-700",
  "scale-orange-700": "scale-orange-700",
  "scale.orange.800": "scale-orange-800",
  "scale-orange-800": "scale-orange-800",
  "scale.orange.900": "scale-orange-900",
  "scale-orange-900": "scale-orange-900",
  "scale.orange.000": "scale-orange-000",
  "scale-orange-000": "scale-orange-000",
  "scale.magenta.100": "scale-magenta-100",
  "scale-magenta-100": "scale-magenta-100",
  "scale.magenta.200": "scale-magenta-200",
  "scale-magenta-200": "scale-magenta-200",
  "scale.magenta.300": "scale-magenta-300",
  "scale-magenta-300": "scale-magenta-300",
  "scale.magenta.400": "scale-magenta-400",
  "scale-magenta-400": "scale-magenta-400",
  "scale.magenta.500": "scale-magenta-500",
  "scale-magenta-500": "scale-magenta-500",
  "scale.magenta.600": "scale-magenta-600",
  "scale-magenta-600": "scale-magenta-600",
  "scale.magenta.700": "scale-magenta-700",
  "scale-magenta-700": "scale-magenta-700",
  "scale.magenta.800": "scale-magenta-800",
  "scale-magenta-800": "scale-magenta-800",
  "scale.magenta.900": "scale-magenta-900",
  "scale-magenta-900": "scale-magenta-900",
  "scale.magenta.000": "scale-magenta-000",
  "scale-magenta-000": "scale-magenta-000",
  "scale.lime.100": "scale-lime-100",
  "scale-lime-100": "scale-lime-100",
  "scale.lime.200": "scale-lime-200",
  "scale-lime-200": "scale-lime-200",
  "scale.lime.300": "scale-lime-300",
  "scale-lime-300": "scale-lime-300",
  "scale.lime.400": "scale-lime-400",
  "scale-lime-400": "scale-lime-400",
  "scale.lime.500": "scale-lime-500",
  "scale-lime-500": "scale-lime-500",
  "scale.lime.600": "scale-lime-600",
  "scale-lime-600": "scale-lime-600",
  "scale.lime.700": "scale-lime-700",
  "scale-lime-700": "scale-lime-700",
  "scale.lime.800": "scale-lime-800",
  "scale-lime-800": "scale-lime-800",
  "scale.lime.900": "scale-lime-900",
  "scale-lime-900": "scale-lime-900",
  "scale.lime.000": "scale-lime-000",
  "scale-lime-000": "scale-lime-000",
};

const allTokensObject = { ...tokensObject, ...scaleTokensObject };

const allTokens = Object.keys(allTokensObject);

export type FuegoTokenNames = keyof typeof tokensObject;

export const Tokens = Object.keys(tokensObject);

export type FuegoScaleTokenNames = keyof typeof scaleTokensObject;

export const ScaleTokens = Object.keys(scaleTokensObject);

export type TailwindPrefix =
  | "bg"
  | "text"
  | "border"
  | "leading"
  | "rounded"
  | "etc";

function createSdk() {
  const theme: Map<string, string> = new Map();
  const extension: Map<string, string> = new Map();
  const aliasMap: Map<string, any> = new Map();
  const themeLoadSubscribers: Set<() => void> = new Set();
  const themeUnloadSubscribers: Set<() => void> = new Set();

  const addCssVars = () => {
    for (let cssVar of [
      ...Array.from(theme.entries()),
      ...Array.from(extension.entries()),
    ]) {
      document.documentElement.style.setProperty("--" + cssVar[0], cssVar[1]);
    }
  };

  const removeCssVars = (keys: Array<string>) => {
    for (let key of keys) {
      document.documentElement.style.removeProperty("--" + key);
    }
  };

  const loadTheme = (newTheme: Map<string, string>): void => {
    for (let cssVar of Array.from(newTheme.entries())) {
      theme.set(cssVar[0], cssVar[1]);
    }

    addCssVars();

    for (let cb of Array.from(themeLoadSubscribers)) {
      cb();
    }
  };

  const loadThemeExtension = <T extends string = string>(
    newExtension: Map<T, string>,
  ): void => {
    for (let cssVar of Array.from(newExtension.entries())) {
      extension.set(cssVar[0], cssVar[1]);
    }

    addCssVars();
  };

  const unloadTheme = (): void => {
    removeCssVars(Array.from(theme.keys()));
    theme.clear();
    for (let cb of Array.from(themeUnloadSubscribers)) {
      cb();
    }
  };

  const unloadThemeExtension = (): void => {
    const keys: Array<string> = Array.from(extension.keys());
    removeCssVars(keys);
    extension.clear();
  };

  const onThemeLoad = (cb: () => void): (() => void) => {
    themeLoadSubscribers.add(cb);

    return () => {
      themeLoadSubscribers.delete(cb);
    };
  };

  const onThemeUnload = (cb: () => void): (() => void) => {
    themeUnloadSubscribers.add(cb);

    return () => {
      themeUnloadSubscribers.delete(cb);
    };
  };

  const addUpdateAlias = <T extends string = string>(
    name: FuegoTokenNames,
    alias: T,
  ): void => {
    if (typeof alias !== "string") {
      throw new Error("Fuego: alias has to be a text value");
    }

    aliasMap.set(alias, name);
  };

  const removeAlias = <T extends string = string>(alias: T): void => {
    aliasMap.delete(alias);
  };

  const getName = (name: string): string => {
    if (allTokensObject[name]) {
      return allTokensObject[name] || "";
    }

    return aliasMap.get(name) || name;
  };

  const themeGet = <T extends string = string>(
    name: FuegoTokenNames | T,
  ): string => {
    return "var(--" + getName(name) + ")";
  };

  const scaleGet = (name: FuegoScaleTokenNames): string => {
    return "var(--" + getName(name) + ")";
  };

  const themeGetValue = <T extends string = string>(
    name: FuegoTokenNames | T,
  ): string => {
    return extension.get(getName(name)) || theme.get(getName(name)) || "";
  };

  const scaleGetValue = (name: FuegoScaleTokenNames): string => {
    return extension.get(getName(name)) || theme.get(getName(name)) || "";
  };

  const themeGetTailwindClass = <T extends string = string>(
    name: T | FuegoTokenNames,
    type: TailwindPrefix,
    prefix: string = "",
  ): string => {
    return [prefix, type, getName(name)].filter(Boolean).join("-");
  };

  const scaleGetTailwindClass = (
    name: FuegoScaleTokenNames,
    type: TailwindPrefix,
    prefix: string = "",
  ): string => {
    return [prefix, type, getName(name)].filter(Boolean).join("-");
  };

  const expose = () => {
    const getEmpty = (): void => {
      const empty = allTokens.map((t) => `['${t}', '']`).join(",\n");
      console.log(`new Map([\n${empty}\n])`);
    };

    const findToken = (val: string): void => {
      const match = allTokens.filter((name) =>
        themeGetValue(name)
          .toLocaleLowerCase()
          .includes(val.toLocaleLowerCase()),
      );

      for (let x of match) {
        console.log(themeGetValue(x), x);
      }
    };

    // Add more dev tools if neccesary.
    // Remember not to expose it on prod.
    (window as any).Fuego = {
      loadTheme,
      unloadTheme,
      themeGet,
      scaleGet,
      themeGetValue,
      themeGetTailwindClass,
      scaleGetValue,
      scaleGetTailwindClass,
      getEmpty,
      findToken,
      Tokens,
      ScaleTokens,
    };
  };

  return {
    loadTheme,
    unloadTheme,
    onThemeLoad,
    onThemeUnload,
    addUpdateAlias,
    removeAlias,
    loadThemeExtension,
    unloadThemeExtension,
    themeGet,
    scaleGet,
    themeGetValue,
    themeGetTailwindClass,
    expose,
    scaleGetValue,
    scaleGetTailwindClass,
    Tokens,
    ScaleTokens,
  };
}

export const Fuego = createSdk();
