/**
 * @fuegokit/tokens 0.20.0
 * Do not edit directly
 * Generated on Sat, 11 May 2024 01:31:20 GMT
 */

const plugin = require("tailwindcss/plugin");

const fuegokitTailwindTypographyPlugin = plugin(function ({
  addUtilities,
  theme,
}) {
  const font = theme("font") ?? {};

  function flattenObject(obj, prefix = "") {
    if (!obj) {
      return [];
    }

    const result = [];
    for (let key in obj) {
      const newPrefix = [prefix, key].join("-");
      if (typeof obj[key] === "string") {
        result.push([newPrefix, obj[key]]);
      } else {
        result.push(...flattenObject(obj[key], newPrefix));
      }
    }

    return result;
  }

  const map = new Map(flattenObject(font));
  const utilities = Array.from(map.entries()).map(([key, value]) => {
    return {
      [".typography-" + key]: { font: value },
    };
  });

  addUtilities(utilities);
});

module.exports = {
  plugins: [fuegokitTailwindTypographyPlugin],
  theme: {
    font: {
      "font-heading-xxsmall": "var(--font-heading-xxsmall)",
      "font-heading-xsmall": "var(--font-heading-xsmall)",
      "font-heading-small": "var(--font-heading-small)",
      "font-heading-medium": "var(--font-heading-medium)",
      "font-heading-large": "var(--font-heading-large)",
      "font-heading-xlarge": "var(--font-heading-xlarge)",
      "font-heading-xxlarge": "var(--font-heading-xxlarge)",
      "font-body": "var(--font-body)",
      "font-body-small": "var(--font-body-small)",
      "font-body-medium": "var(--font-body-medium)",
      "font-body-large": "var(--font-body-large)",
      "font-body-xlarge": "var(--font-body-xlarge)",
      "font-ui": "var(--font-ui)",
      "font-ui-small": "var(--font-ui-small)",
      "font-caption": "var(--font-caption)",
      "font-code": "var(--font-code)",
      "font-code-xsmall": "var(--font-code-xsmall)",
      "font-code-small": "var(--font-code-small)",
      "font-code-medium": "var(--font-code-medium)",
      "font-display": "var(--font-display)",
      "font-display-medium": "var(--font-display-medium)",
    },
    spacing: {
      "space-0": "var(--space-0)",
      "space-1": "var(--space-1)",
      "space-2": "var(--space-2)",
      "space-3": "var(--space-3)",
      "space-4": "var(--space-4)",
      "space-5": "var(--space-5)",
      "space-6": "var(--space-6)",
      "space-7": "var(--space-7)",
      "space-8": "var(--space-8)",
      "space-9": "var(--space-9)",
      "space-10": "var(--space-10)",
      "space-11": "var(--space-11)",
      "space-12": "var(--space-12)",
      "size-0": "var(--size-0)",
      "size-4": "var(--size-4)",
      "size-8": "var(--size-8)",
      "size-12": "var(--size-12)",
      "size-16": "var(--size-16)",
      "size-20": "var(--size-20)",
      "size-24": "var(--size-24)",
      "size-28": "var(--size-28)",
      "size-32": "var(--size-32)",
      "size-36": "var(--size-36)",
      "size-40": "var(--size-40)",
      "size-44": "var(--size-44)",
      "size-48": "var(--size-48)",
      "size-64": "var(--size-64)",
      "size-80": "var(--size-80)",
      "size-96": "var(--size-96)",
      "size-112": "var(--size-112)",
      "size-128": "var(--size-128)",
      "size-144": "var(--size-144)",
    },
    borderRadius: {
      "radii-0": "var(--radii-0)",
      "radii-1": "var(--radii-1)",
      "radii-2": "var(--radii-2)",
      "radii-3": "var(--radii-3)",
      "radii-4": "var(--radii-4)",
      "radii-5": "var(--radii-5)",
    },
    fontFamily: {
      "fontStack-sansSerif": "var(--fontStack-sansSerif)",
      "fontStack-monospace": "var(--fontStack-monospace)",
      "fontStack-title": "var(--fontStack-title)",
      "fontStack-body": "var(--fontStack-body)",
      "fontStack-normal": "var(--fontStack-normal)",
      "fontStack-mono": "var(--fontStack-mono)",
    },
    fontSize: {
      "fontSize-0": "var(--fontSize-0)",
      "fontSize-1": "var(--fontSize-1)",
      "fontSize-2": "var(--fontSize-2)",
      "fontSize-3": "var(--fontSize-3)",
      "fontSize-4": "var(--fontSize-4)",
      "fontSize-5": "var(--fontSize-5)",
      "fontSize-6": "var(--fontSize-6)",
      "fontSize-7": "var(--fontSize-7)",
      "fontSize-8": "var(--fontSize-8)",
      "fontSize-9": "var(--fontSize-9)",
      "fontSize-10": "var(--fontSize-10)",
      "fontSize-11": "var(--fontSize-11)",
      "fontSize-12": "var(--fontSize-12)",
      "fontSize-13": "var(--fontSize-13)",
    },
    lineHeight: {
      "lineHeight-0": "var(--lineHeight-0)",
      "lineHeight-1": "var(--lineHeight-1)",
      "lineHeight-2": "var(--lineHeight-2)",
      "lineHeight-3": "var(--lineHeight-3)",
      "lineHeight-4": "var(--lineHeight-4)",
      "lineHeight-5": "var(--lineHeight-5)",
      "lineHeight-6": "var(--lineHeight-6)",
      lineHeight: "var(--lineHeight)",
      "lineHeight-condensed": "var(--lineHeight-condensed)",
      "lineHeight-condensedUltra": "var(--lineHeight-condensedUltra)",
      "lineHeight-relaxed": "var(--lineHeight-relaxed)",
    },
    fontWeight: {
      "fontWeight-thin": "var(--fontWeight-thin)",
      "fontWeight-extraLight": "var(--fontWeight-extraLight)",
      "fontWeight-light": "var(--fontWeight-light)",
      "fontWeight-normal": "var(--fontWeight-normal)",
      "fontWeight-medium": "var(--fontWeight-medium)",
      "fontWeight-semiBold": "var(--fontWeight-semiBold)",
      "fontWeight-semibold": "var(--fontWeight-semibold)",
      "fontWeight-bold": "var(--fontWeight-bold)",
      "fontWeight-extraBold": "var(--fontWeight-extraBold)",
      "fontWeight-black": "var(--fontWeight-black)",
    },
    colors: {
      "scale-white": "var(--scale-white)",
      "scale-black": "var(--scale-black)",
      "scale-gray-100": "var(--scale-gray-100)",
      "scale-gray-200": "var(--scale-gray-200)",
      "scale-gray-300": "var(--scale-gray-300)",
      "scale-gray-400": "var(--scale-gray-400)",
      "scale-gray-500": "var(--scale-gray-500)",
      "scale-gray-600": "var(--scale-gray-600)",
      "scale-gray-700": "var(--scale-gray-700)",
      "scale-gray-800": "var(--scale-gray-800)",
      "scale-gray-900": "var(--scale-gray-900)",
      "scale-gray-000": "var(--scale-gray-000)",
      "scale-neutral-100": "var(--scale-neutral-100)",
      "scale-neutral-200": "var(--scale-neutral-200)",
      "scale-neutral-300": "var(--scale-neutral-300)",
      "scale-neutral-400": "var(--scale-neutral-400)",
      "scale-neutral-500": "var(--scale-neutral-500)",
      "scale-neutral-600": "var(--scale-neutral-600)",
      "scale-neutral-700": "var(--scale-neutral-700)",
      "scale-neutral-800": "var(--scale-neutral-800)",
      "scale-neutral-900": "var(--scale-neutral-900)",
      "scale-neutral-1000": "var(--scale-neutral-1000)",
      "scale-neutral-1100": "var(--scale-neutral-1100)",
      "scale-neutral-000": "var(--scale-neutral-000)",
      "scale-neutralAlpha-100": "var(--scale-neutralAlpha-100)",
      "scale-neutralAlpha-200": "var(--scale-neutralAlpha-200)",
      "scale-neutralAlpha-300": "var(--scale-neutralAlpha-300)",
      "scale-neutralAlpha-400": "var(--scale-neutralAlpha-400)",
      "scale-neutralAlpha-500": "var(--scale-neutralAlpha-500)",
      "scale-neutralAlpha-600": "var(--scale-neutralAlpha-600)",
      "scale-neutralAlpha-700": "var(--scale-neutralAlpha-700)",
      "scale-neutralAlpha-800": "var(--scale-neutralAlpha-800)",
      "scale-neutralAlpha-900": "var(--scale-neutralAlpha-900)",
      "scale-neutralAlpha-000": "var(--scale-neutralAlpha-000)",
      "scale-blue-100": "var(--scale-blue-100)",
      "scale-blue-200": "var(--scale-blue-200)",
      "scale-blue-300": "var(--scale-blue-300)",
      "scale-blue-400": "var(--scale-blue-400)",
      "scale-blue-500": "var(--scale-blue-500)",
      "scale-blue-600": "var(--scale-blue-600)",
      "scale-blue-700": "var(--scale-blue-700)",
      "scale-blue-800": "var(--scale-blue-800)",
      "scale-blue-900": "var(--scale-blue-900)",
      "scale-blue-000": "var(--scale-blue-000)",
      "scale-teal-100": "var(--scale-teal-100)",
      "scale-teal-200": "var(--scale-teal-200)",
      "scale-teal-300": "var(--scale-teal-300)",
      "scale-teal-400": "var(--scale-teal-400)",
      "scale-teal-500": "var(--scale-teal-500)",
      "scale-teal-600": "var(--scale-teal-600)",
      "scale-teal-700": "var(--scale-teal-700)",
      "scale-teal-800": "var(--scale-teal-800)",
      "scale-teal-900": "var(--scale-teal-900)",
      "scale-teal-000": "var(--scale-teal-000)",
      "scale-purple-100": "var(--scale-purple-100)",
      "scale-purple-200": "var(--scale-purple-200)",
      "scale-purple-300": "var(--scale-purple-300)",
      "scale-purple-400": "var(--scale-purple-400)",
      "scale-purple-500": "var(--scale-purple-500)",
      "scale-purple-600": "var(--scale-purple-600)",
      "scale-purple-700": "var(--scale-purple-700)",
      "scale-purple-800": "var(--scale-purple-800)",
      "scale-purple-900": "var(--scale-purple-900)",
      "scale-purple-000": "var(--scale-purple-000)",
      "scale-green-100": "var(--scale-green-100)",
      "scale-green-200": "var(--scale-green-200)",
      "scale-green-300": "var(--scale-green-300)",
      "scale-green-400": "var(--scale-green-400)",
      "scale-green-500": "var(--scale-green-500)",
      "scale-green-600": "var(--scale-green-600)",
      "scale-green-700": "var(--scale-green-700)",
      "scale-green-800": "var(--scale-green-800)",
      "scale-green-900": "var(--scale-green-900)",
      "scale-green-000": "var(--scale-green-000)",
      "scale-yellow-100": "var(--scale-yellow-100)",
      "scale-yellow-200": "var(--scale-yellow-200)",
      "scale-yellow-300": "var(--scale-yellow-300)",
      "scale-yellow-400": "var(--scale-yellow-400)",
      "scale-yellow-500": "var(--scale-yellow-500)",
      "scale-yellow-600": "var(--scale-yellow-600)",
      "scale-yellow-700": "var(--scale-yellow-700)",
      "scale-yellow-800": "var(--scale-yellow-800)",
      "scale-yellow-900": "var(--scale-yellow-900)",
      "scale-yellow-000": "var(--scale-yellow-000)",
      "scale-red-100": "var(--scale-red-100)",
      "scale-red-200": "var(--scale-red-200)",
      "scale-red-300": "var(--scale-red-300)",
      "scale-red-400": "var(--scale-red-400)",
      "scale-red-500": "var(--scale-red-500)",
      "scale-red-600": "var(--scale-red-600)",
      "scale-red-700": "var(--scale-red-700)",
      "scale-red-800": "var(--scale-red-800)",
      "scale-red-900": "var(--scale-red-900)",
      "scale-red-000": "var(--scale-red-000)",
      "scale-orange-100": "var(--scale-orange-100)",
      "scale-orange-200": "var(--scale-orange-200)",
      "scale-orange-300": "var(--scale-orange-300)",
      "scale-orange-400": "var(--scale-orange-400)",
      "scale-orange-500": "var(--scale-orange-500)",
      "scale-orange-600": "var(--scale-orange-600)",
      "scale-orange-700": "var(--scale-orange-700)",
      "scale-orange-800": "var(--scale-orange-800)",
      "scale-orange-900": "var(--scale-orange-900)",
      "scale-orange-000": "var(--scale-orange-000)",
      "scale-magenta-100": "var(--scale-magenta-100)",
      "scale-magenta-200": "var(--scale-magenta-200)",
      "scale-magenta-300": "var(--scale-magenta-300)",
      "scale-magenta-400": "var(--scale-magenta-400)",
      "scale-magenta-500": "var(--scale-magenta-500)",
      "scale-magenta-600": "var(--scale-magenta-600)",
      "scale-magenta-700": "var(--scale-magenta-700)",
      "scale-magenta-800": "var(--scale-magenta-800)",
      "scale-magenta-900": "var(--scale-magenta-900)",
      "scale-magenta-000": "var(--scale-magenta-000)",
      "scale-lime-100": "var(--scale-lime-100)",
      "scale-lime-200": "var(--scale-lime-200)",
      "scale-lime-300": "var(--scale-lime-300)",
      "scale-lime-400": "var(--scale-lime-400)",
      "scale-lime-500": "var(--scale-lime-500)",
      "scale-lime-600": "var(--scale-lime-600)",
      "scale-lime-700": "var(--scale-lime-700)",
      "scale-lime-800": "var(--scale-lime-800)",
      "scale-lime-900": "var(--scale-lime-900)",
      "scale-lime-000": "var(--scale-lime-000)",
      surface: "var(--surface)",
      "surface-hovered": "var(--surface-hovered)",
      "surface-pressed": "var(--surface-pressed)",
      "surface-sunken": "var(--surface-sunken)",
      "surface-raised": "var(--surface-raised)",
      "surface-raised-hovered": "var(--surface-raised-hovered)",
      "surface-raised-pressed": "var(--surface-raised-pressed)",
      "surface-overlay": "var(--surface-overlay)",
      "surface-overlay-hovered": "var(--surface-overlay-hovered)",
      "surface-overlay-pressed": "var(--surface-overlay-pressed)",
      "shadow-raised": "var(--shadow-raised)",
      "shadow-overlay": "var(--shadow-overlay)",
      "shadow-overflow": "var(--shadow-overflow)",
      "shadow-overflow-spread": "var(--shadow-overflow-spread)",
      "shadow-overflow-perimeter": "var(--shadow-overflow-perimeter)",
      border: "var(--border)",
      "border-selected": "var(--border-selected)",
      "border-focused": "var(--border-focused)",
      "border-subtle": "var(--border-subtle)",
      "border-input": "var(--border-input)",
      "border-inverse": "var(--border-inverse)",
      "border-disabled": "var(--border-disabled)",
      "border-brand": "var(--border-brand)",
      "border-danger": "var(--border-danger)",
      "border-warning": "var(--border-warning)",
      "border-success": "var(--border-success)",
      "border-discovery": "var(--border-discovery)",
      "border-information": "var(--border-information)",
      "border-accent-blue": "var(--border-accent-blue)",
      "border-accent-red": "var(--border-accent-red)",
      "border-accent-orange": "var(--border-accent-orange)",
      "border-accent-yellow": "var(--border-accent-yellow)",
      "border-accent-green": "var(--border-accent-green)",
      "border-accent-purple": "var(--border-accent-purple)",
      "border-accent-teal": "var(--border-accent-teal)",
      "border-accent-magenta": "var(--border-accent-magenta)",
      "border-accent-gray": "var(--border-accent-gray)",
      "border-table": "var(--border-table)",
      "background-accent-blue-subtlest":
        "var(--background-accent-blue-subtlest)",
      "background-accent-blue-subtler": "var(--background-accent-blue-subtler)",
      "background-accent-blue-subtle": "var(--background-accent-blue-subtle)",
      "background-accent-blue-bolder": "var(--background-accent-blue-bolder)",
      "background-accent-red-subtlest": "var(--background-accent-red-subtlest)",
      "background-accent-red-subtler": "var(--background-accent-red-subtler)",
      "background-accent-red-subtle": "var(--background-accent-red-subtle)",
      "background-accent-red-bolder": "var(--background-accent-red-bolder)",
      "background-accent-orange-subtlest":
        "var(--background-accent-orange-subtlest)",
      "background-accent-orange-subtler":
        "var(--background-accent-orange-subtler)",
      "background-accent-orange-subtle":
        "var(--background-accent-orange-subtle)",
      "background-accent-orange-bolder":
        "var(--background-accent-orange-bolder)",
      "background-accent-yellow-subtlest":
        "var(--background-accent-yellow-subtlest)",
      "background-accent-yellow-subtler":
        "var(--background-accent-yellow-subtler)",
      "background-accent-yellow-subtle":
        "var(--background-accent-yellow-subtle)",
      "background-accent-yellow-bolder":
        "var(--background-accent-yellow-bolder)",
      "background-accent-green-subtlest":
        "var(--background-accent-green-subtlest)",
      "background-accent-green-subtler":
        "var(--background-accent-green-subtler)",
      "background-accent-green-subtle": "var(--background-accent-green-subtle)",
      "background-accent-green-bolder": "var(--background-accent-green-bolder)",
      "background-accent-purple-subtlest":
        "var(--background-accent-purple-subtlest)",
      "background-accent-purple-subtler":
        "var(--background-accent-purple-subtler)",
      "background-accent-purple-subtle":
        "var(--background-accent-purple-subtle)",
      "background-accent-purple-bolder":
        "var(--background-accent-purple-bolder)",
      "background-accent-teal-subtlest":
        "var(--background-accent-teal-subtlest)",
      "background-accent-teal-subtler": "var(--background-accent-teal-subtler)",
      "background-accent-teal-subtle": "var(--background-accent-teal-subtle)",
      "background-accent-teal-bolder": "var(--background-accent-teal-bolder)",
      "background-accent-magenta-subtlest":
        "var(--background-accent-magenta-subtlest)",
      "background-accent-magenta-subtler":
        "var(--background-accent-magenta-subtler)",
      "background-accent-magenta-subtle":
        "var(--background-accent-magenta-subtle)",
      "background-accent-magenta-bolder":
        "var(--background-accent-magenta-bolder)",
      "background-accent-gray-subtlest":
        "var(--background-accent-gray-subtlest)",
      "background-accent-gray-subtler": "var(--background-accent-gray-subtler)",
      "background-accent-gray-subtle": "var(--background-accent-gray-subtle)",
      "background-accent-gray-bolder": "var(--background-accent-gray-bolder)",
      "background-accent-lime-subtlest":
        "var(--background-accent-lime-subtlest)",
      "background-accent-lime-subtler": "var(--background-accent-lime-subtler)",
      "background-accent-lime-subtle": "var(--background-accent-lime-subtle)",
      "background-accent-lime-bolder": "var(--background-accent-lime-bolder)",
      "background-input": "var(--background-input)",
      "background-input-hovered": "var(--background-input-hovered)",
      "background-input-pressed": "var(--background-input-pressed)",
      "background-inverse-subtle": "var(--background-inverse-subtle)",
      "background-inverse-subtle-hovered":
        "var(--background-inverse-subtle-hovered)",
      "background-inverse-subtle-pressed":
        "var(--background-inverse-subtle-pressed)",
      "background-neutral": "var(--background-neutral)",
      "background-neutral-hovered": "var(--background-neutral-hovered)",
      "background-neutral-pressed": "var(--background-neutral-pressed)",
      "background-neutral-subtle": "var(--background-neutral-subtle)",
      "background-neutral-subtle-hovered":
        "var(--background-neutral-subtle-hovered)",
      "background-neutral-subtle-pressed":
        "var(--background-neutral-subtle-pressed)",
      "background-neutral-bold": "var(--background-neutral-bold)",
      "background-neutral-bold-hovered":
        "var(--background-neutral-bold-hovered)",
      "background-neutral-bold-pressed":
        "var(--background-neutral-bold-pressed)",
      "background-brand-subtlest": "var(--background-brand-subtlest)",
      "background-brand-subtlest-hovered":
        "var(--background-brand-subtlest-hovered)",
      "background-brand-subtlest-pressed":
        "var(--background-brand-subtlest-pressed)",
      "background-brand-bold": "var(--background-brand-bold)",
      "background-brand-bold-hovered": "var(--background-brand-bold-hovered)",
      "background-brand-bold-pressed": "var(--background-brand-bold-pressed)",
      "background-brand-boldest": "var(--background-brand-boldest)",
      "background-brand-boldest-hovered":
        "var(--background-brand-boldest-hovered)",
      "background-brand-boldest-pressed":
        "var(--background-brand-boldest-pressed)",
      "background-selected": "var(--background-selected)",
      "background-selected-hovered": "var(--background-selected-hovered)",
      "background-selected-pressed": "var(--background-selected-pressed)",
      "background-selected-bold": "var(--background-selected-bold)",
      "background-selected-bold-hovered":
        "var(--background-selected-bold-hovered)",
      "background-selected-bold-pressed":
        "var(--background-selected-bold-pressed)",
      "background-disabled": "var(--background-disabled)",
      "background-information": "var(--background-information)",
      "background-information-hovered": "var(--background-information-hovered)",
      "background-information-pressed": "var(--background-information-pressed)",
      "background-information-bold": "var(--background-information-bold)",
      "background-information-bold-hovered":
        "var(--background-information-bold-hovered)",
      "background-information-bold-pressed":
        "var(--background-information-bold-pressed)",
      "background-danger": "var(--background-danger)",
      "background-danger-hovered": "var(--background-danger-hovered)",
      "background-danger-pressed": "var(--background-danger-pressed)",
      "background-danger-bold": "var(--background-danger-bold)",
      "background-danger-bold-hovered": "var(--background-danger-bold-hovered)",
      "background-danger-bold-pressed": "var(--background-danger-bold-pressed)",
      "background-success": "var(--background-success)",
      "background-success-hovered": "var(--background-success-hovered)",
      "background-success-pressed": "var(--background-success-pressed)",
      "background-success-bold": "var(--background-success-bold)",
      "background-success-bold-hovered":
        "var(--background-success-bold-hovered)",
      "background-success-bold-pressed":
        "var(--background-success-bold-pressed)",
      "background-discovery": "var(--background-discovery)",
      "background-discovery-hovered": "var(--background-discovery-hovered)",
      "background-discovery-pressed": "var(--background-discovery-pressed)",
      "background-discovery-bold": "var(--background-discovery-bold)",
      "background-discovery-bold-hovered":
        "var(--background-discovery-bold-hovered)",
      "background-discovery-bold-pressed":
        "var(--background-discovery-bold-pressed)",
      "background-warning": "var(--background-warning)",
      "background-warning-hovered": "var(--background-warning-hovered)",
      "background-warning-pressed": "var(--background-warning-pressed)",
      "background-warning-bold": "var(--background-warning-bold)",
      "background-warning-bold-hovered":
        "var(--background-warning-bold-hovered)",
      "background-warning-bold-pressed":
        "var(--background-warning-bold-pressed)",
      text: "var(--text)",
      "text-subtle": "var(--text-subtle)",
      "text-subtlest": "var(--text-subtlest)",
      "text-disabled": "var(--text-disabled)",
      "text-selected": "var(--text-selected)",
      "text-inverse": "var(--text-inverse)",
      "text-success": "var(--text-success)",
      "text-danger": "var(--text-danger)",
      "text-information": "var(--text-information)",
      "text-warning": "var(--text-warning)",
      "text-warning-inverse": "var(--text-warning-inverse)",
      "text-discovery": "var(--text-discovery)",
      "text-brand": "var(--text-brand)",
      "text-accent-blue": "var(--text-accent-blue)",
      "text-accent-blue-bolder": "var(--text-accent-blue-bolder)",
      "text-accent-red": "var(--text-accent-red)",
      "text-accent-red-bolder": "var(--text-accent-red-bolder)",
      "text-accent-orange": "var(--text-accent-orange)",
      "text-accent-orange-bolder": "var(--text-accent-orange-bolder)",
      "text-accent-yellow": "var(--text-accent-yellow)",
      "text-accent-yellow-bolder": "var(--text-accent-yellow-bolder)",
      "text-accent-green": "var(--text-accent-green)",
      "text-accent-green-bolder": "var(--text-accent-green-bolder)",
      "text-accent-purple": "var(--text-accent-purple)",
      "text-accent-purple-bolder": "var(--text-accent-purple-bolder)",
      "text-accent-teal": "var(--text-accent-teal)",
      "text-accent-teal-bolder": "var(--text-accent-teal-bolder)",
      "text-accent-magenta": "var(--text-accent-magenta)",
      "text-accent-magenta-bolder": "var(--text-accent-magenta-bolder)",
      "text-accent-gray": "var(--text-accent-gray)",
      "text-accent-gray-bolder": "var(--text-accent-gray-bolder)",
      "text-accent-lime": "var(--text-accent-lime)",
      "text-accent-lime-bolder": "var(--text-accent-lime-bolder)",
      link: "var(--link)",
      "link-hovered": "var(--link-hovered)",
      "link-pressed": "var(--link-pressed)",
      "link-visited": "var(--link-visited)",
      "icon-accent-blue": "var(--icon-accent-blue)",
      "icon-accent-red": "var(--icon-accent-red)",
      "icon-accent-orange": "var(--icon-accent-orange)",
      "icon-accent-yellow": "var(--icon-accent-yellow)",
      "icon-accent-green": "var(--icon-accent-green)",
      "icon-accent-purple": "var(--icon-accent-purple)",
      "icon-accent-teal": "var(--icon-accent-teal)",
      "icon-accent-magenta": "var(--icon-accent-magenta)",
      "icon-accent-gray": "var(--icon-accent-gray)",
      "icon-accent-lime": "var(--icon-accent-lime)",
      icon: "var(--icon)",
      "icon-subtle": "var(--icon-subtle)",
      "icon-inverse": "var(--icon-inverse)",
      "icon-disabled": "var(--icon-disabled)",
      "icon-brand": "var(--icon-brand)",
      "icon-selected": "var(--icon-selected)",
      "icon-danger": "var(--icon-danger)",
      "icon-success": "var(--icon-success)",
      "icon-discovery": "var(--icon-discovery)",
      "icon-information": "var(--icon-information)",
      "icon-warning": "var(--icon-warning)",
      "icon-warning-inverse": "var(--icon-warning-inverse)",
      blanket: "var(--blanket)",
      "blanket-selected": "var(--blanket-selected)",
      "blanket-danger": "var(--blanket-danger)",
    },
  },
};
